enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
enable-update-checks = true
enabled = false

[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
enable-update-checks = true
enabled = false

[Reddit-Morphe]
app-name = "Reddit"
rv-brand = "Morphe"
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"
enabled = false

[GooglePhotos]
build-mode = "both"
patches-source = "RookieEnough/De-Vanced"
rv-brand = "DeVanced"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"
enable-update-checks = true
enabled = false

[Twitter]
patches-source = "crimera/piko-newx"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
version = "latest"
included-patches = "'NewX: Restore Twitter branding'"
enable-update-checks = true
enabled = false

[Music]
enabled = false
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube]
enabled = false
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Twitch]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"

[KineStop]
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
cli-version = "latest"
rv-brand = "Morphe"
build-mode = "module"
arch = "all"
# softonic-dlurl = "https://kinestop-car-sickness-aid.en.softonic.com/android"
direct-dlurl = "https://github.com/hkopenclaw/morphe-apks/releases/download/com.urbandroid.kinestop-5.1/com.urbandroid.kinestop-5.1-all.apk"
enabled = false

[Pixiv]
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
cli-version = "latest"
rv-brand = "DeVanced"
build-mode = "module"
arch = "all"
# uptodown-dlurl = "https://pixiv.en.uptodown.com/android"
direct-dlurl = "https://github.com/hkopenclaw/morphe-apks/releases/download/jp.pxv.android-6.141.1/jp.pxv.android-6.141.1-all.apk"
version = "6.141.1"
