enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
enabled = false

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
enabled = false

[GooglePhotos]
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "de-revanced"
build-mode = "module"
arch = "arm64-v8a"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
direct-dlurl = "https://dw.uptodown.net/dwn/3biw8kf5gTQ82QEkKA9UJa7a25f5DajySQ24Z0He9l0QJgZfX3chyOyeK7ThSLqcAwfT2HiZahOnRoKNIx1xZ-PZQqNL2UFI6f8E3I77mmjUIqv_M5L--qr6WPsYQfVl/3nQIYwHfd0mL_wyXIVGGoXkvVHYFjyXqU_oVB1NNpD2Z-HLewkVd7xEMdwGNQWJFfXEIFlF_gaByAXxNTKnD3syr5Do5DbIgVXMfyXgtmXYYrR3OvrHnVTfKKrshbgsL/DZtk5ieRxaJEXqXR8P53LidBR4LTb03Sk_ZI16n7ux7DpzznJQfLpoHRSWrfkP8h3hWRx100dQNywGl0VXx9jQ5Mb_XBcmfJOejoPa85ik2xbIr4WwliA5Htgx-itZp7/uptodown-com.google.android.apps.photos.apk"
