enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
enabled = false

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
enabled = false

[GooglePhotos]
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "de-revanced"
build-mode = "module"
arch = "arm64-v8a"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
enabled = false

[pixiv]
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "de-revanced"
build-mode = "module"
# arch = "arm64-v8a"
arch = "all"
# uptodown-dlurl = "https://pixiv.en.uptodown.com/android"
direct-dlurl = "https://github.com/hkopenclaw/morphe-magisk-module/releases/download/jp.pxv.android_6.189.0/jp.pxv.android_6.189.0.apk"
